package scoring

// contentIndicators are class/id patterns that indicate content elements
// JavaScript original code:
//
//	const contentIndicators = [
//		'admonition',
//		'article',
//		'content',
//		'entry',
//		'image',
//		'img',
//		'font',
//		'figure',
//		'figcaption',
//		'pre',
//		'main',
//		'post',
//		'story',
//		'table'
//	];
var contentIndicators = []string{
	"admonition",
	"article",
	"content",
	"entry",
	"image",
	"img",
	"font",
	"figure",
	"figcaption",
	"pre",
	"main",
	"post",
	"story",
	"table",
}

// navigationIndicators are text patterns that indicate navigation/non-content
// JavaScript original code:
//
//	const navigationIndicators = [
//		'advertisement',
//		'all rights reserved',
//		'banner',
//		'cookie',
//		'comments',
//		'copyright',
//		'follow me',
//		'follow us',
//		'footer',
//		'header',
//		'homepage',
//		'login',
//		'menu',
//		'more articles',
//		'more like this',
//		'most read',
//		'nav',
//		'navigation',
//		'newsletter',
//		'newsletter',
//		'popular',
//		'privacy',
//		'recommended',
//		'register',
//		'related',
//		'responses',
//		'share',
//		'sidebar',
//		'sign in',
//		'sign up',
//		'signup',
//		'social',
//		'sponsored',
//		'subscribe',
//		'subscribe',
//		'terms',
//		'trending'
//	];
var navigationIndicators = []string{
	"advertisement",
	"all rights reserved",
	"banner",
	"cookie",
	"comments",
	"copyright",
	"follow me",
	"follow us",
	"footer",
	"header",
	"homepage",
	"login",
	"menu",
	"more articles",
	"more like this",
	"most read",
	"nav",
	"navigation",
	"newsletter",
	"popular",
	"privacy",
	"recommended",
	"register",
	"related",
	"responses",
	"share",
	"sidebar",
	"sign in",
	"sign up",
	"signup",
	"social",
	"sponsored",
	"subscribe",
	"terms",
	"trending",
}
