package constants

var partialSelectorsB = []string{
	"_modal",
	"-modal",
	"more-",
	"morenews",
	"morestories",
	"more_wrapper",
	"most-read",
	"move-helper",
	"mw-editsection",
	"mw-cite-backlink",
	"mw-indicators",
	"mw-jump-link",
	"nav-",
	"nav_",
	"navigation-post",
	"next-",
	"next_prev",
	"no-script",
	"newsgallery",
	"news-story-title",
	"newsletter_",
	"newsletterbanner",
	"newslettercontainer",
	"newsletter-form",
	"newsletter-signup",
	"newslettersignup",
	"newsletterwidget",
	"newsletterwrapper",
	"not-found",
	"notessection",
	"nomobile",
	"noprint",
	"open-slideshow",
	"originally-published", // Mercury News
	"other-blogs",
	"outline-view",
	"pagehead",
	"page-header",
	"page-title",
	"paywall_message",
	"-partners",
	"permission-",
	"plea",
	"popular",
	"popup_links",
	"pop_stories",
	"pop-up",
	"post__author",
	"post-author",
	"post-bottom",
	"post__category",
	"postcomment",
	"postdate",
	"post-date",
	"post_date",
	"post-details",
	"post-feeds",
	"postinfo",
	"post-info",
	"post_info",
	"post-inline-date",
	"post-links",
	"postlist",
	"post_list",
	"post_meta",
	"post-meta",
	"postmeta",
	"post_more",
	"postnavi",
	"post-navigation",
	"postpath",
	"post-preview",
	"postsnippet",
	"post_snippet",
	"post-snippet",
	"post-subject",
	"posttax",
	"post-tax",
	"post_tax",
	"posttag",
	"post_tag",
	"post-tag",
	"post_time",
	"posttitle",
	"post-title",
	"post_title",
	"post__title",
	"post-ufi-button",
	"prev-post",
	"prevnext",
	"prev_next",
	"prev-next",
	"previousnext",
	"press-inquiries",
	"print-none",
	"print-header",
	"print:hidden",
	"privacy-notice",
	"privacy-settings",
	"profile",
	//	'promo',
	"promo_article",
	"promo-bar",
	"promo-box",
	"pubdate",
	"pub_date",
	"pub-date",
	"publish_date",
	"publish-date",
	"publication-date",
	"publicationName", // Medium

	"qr-code",
	"qr_code",
	"quick_up",

	"_rail",
	"ratingssection",
	"read_also",
	"readmore",
	"read-next",
	"read_next",
	"read_time",
	"read-time",
	"reading_time",
	"reading-time",
	"reading-list",
	"recent-",
	"recent-articles",
	"recentpost",
	"recent_post",
	"recent-post",
	"recommend",
	"redirectedfrom",
	"recirc",
	"register",
	"related",
	"relevant",
	"reversefootnote",
	"robots-nocontent",
	"_rss",
	"rss-link",

	"screen-reader-text",
	"scroll_to",
	"scroll-to",
	"_search",
	"-search",
	"section-nav",
	"series-banner",
	//	'share',
	//	'-share', scitechdaily.com
	"share-box",
	"sharedaddy",
	"share-icons",
	"sharelinks",
	"share-post",
	"share-print",
	"share-section",
	"sharing_",
	"shariff-",
	"show-for-print",
	"sidebartitle",
	//	'sidebar_',
	"sidebar-content",
	"sidebar-wrapper",
	"sideitems",
	"sidebar-author",
	"sidebar-item",
	"side-box",
	"side-logo",
	"sign-in-gate",
	"similar-",
	"similar_",
	"similars-",
	"site-index",
	"site-header",
	"siteheader",
	"site-logo",
	"site-name",
	"site-wordpress",
	//	'skip-',
	"skip-link",
	"skip-content",
	"skip-to-content",
	"skip-to-main",
	"skip-main",
	"skip-nav",
	"skip-navigation",
	"c-skip-link",
	"_skip-link",
	"-skip-link",
	"skip-link-",
	"-slider",
	"slug-wrap",
	//	'social',
	"social-author",
	"social-shar",
	"social-date",
	"speechify-ignore",
	"speedbump",
	"sponsor",
	"springercitation",
	"sr-only",
	//	'-stats',
	"_stats",
	//	'sticky',
	"story-date",
	"story-navigation",
	"storyreadtime", // Medium
	"storysmall",
	"storypublishdate", // Medium
	"subject-label",
	"subhead",
	"submenu",
	//	'subscribe',
	"-subscribe-",
	"subscriber-drive",
	"subscription-",

	"_tags",
	"tags__item",
	"tag_list",
	"tag-list",
	"taxonomy",
	//	'table-content',
	"table-of-contents",
	"tblc",
	"tabs-",
	//	'teaser', Nature
	"terminaltout",
	"time-rubric",
	"timestamp",
	"time-read",
	"time-to-read",
	"tip_off",
	"tiptout",
	"-tout-",
	//	'-toc',
	"toc-container",
	"toggle-caption",
	//	'toolbar', prism.js
	"tooltip-content",
	"topbar",
	"subnavbar",
	"topic-authors",
	"topic-footer",
	"topic-list",
	"topic-subnav",
	//	'top-section',
	"top-wrapper",
	"tree-item",
	"trending",
	"trust-feat",
	"trust-badge",
	"trust-project",
	"chakra-badge",
	"twitter",
	"twiblock",

	"u-hide",
	"upsell",

	"viewbottom",
	"view-language",
	"yarpp-related",
	"visually-hidden",
	"welcomebox",
	"widget_pages",
	//	'widget-'
	// Webflow form state messages — shown after form submit, never article content
	"w-form-done",
	"w-form-fail",
}
